### ISSUE TITLE
Update si-Add template files for Letters and Fiction

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_SiteIndex#11]
We need to do some speedy regex corrections to [si-Add_LtrsNew_2019.xml](https://github.com/DigitalMitford/DM_SiteIndex/blob/master/si_Add_IP/si-Add_LtrsNew_2019.xml) to update the `<occupation/>` elements to use our new `@type` and `@subtype` values.

**Comment by ebeshero** [comment]
And we need to let @lmwilson know when we're finished with that.

**Comment by amberpeddicord** [comment]
@lmwilson Both files are updated.

**Comment by ebeshero** [comment]
@lmwilson We made sure all the `<occupation type="" subtype""/>` elements in BOTH files are up to date with the current schema, and we also updated things like how we are currently handling genus and species names. Hope this helps!
