### ISSUE TITLE
Test SI Schema on SI_Add files

### ISSUE THREAD

**Issue by ebeshero** [DigitalMitford/DM_SiteIndex#3]
@lmwilson Now that we have a new schema for SI files, you should set the new schema lines (and comment out old schema lines) in your si_Add files (all of them in both directories) to test them out. If you see anything being flagged that doesn't make sense, let me know!

The proper new schema lines are posted on this file: 
https://github.com/DigitalMitford/DM_SiteIndex/blob/master/si_Add_IP/si-Add-CharlesI_FindensT_Rienzi_New.xml

I think my schema rules that help with finding possible duplicates are not working, so I will keep debugging the SI schema, too. Keep doing a `git pull` when you start working in the likely event that I've pushed updates to the schema.

**Comment by lmwilson** [comment]
@ebeshero I'm getting a message that says "element occupation not allowed anywhere."  ??

**Comment by ebeshero** [comment]
@lmwilson Hmm. Does that happen when you delete an old occupation element and try to add a new one? If so, I may need to add our customized occupation element to the person content model...

**Comment by ebeshero** [comment]
@lmwilson Copy a snip of your code here using those tic marks so I can see what you are trying?

**Comment by lmwilson** [comment]
Not sure I did the tic mark thing right but I did upload a so-far corrected version of the file, if you can access that also. I wasn't sure if we changed something in the sort key (I didn't think we changed historical_people, but maybe?) Or if I needed to put the occupation tags in a different place?

`<div type="historical_people">
<listPerson sortKey="histPersons">
             <person xml:id="Becket_Thos" sex="m">
                <persName>Thomas Becket</persName>
                <persName>
                   <surname>Becket</surname>
                   <forename>Thomas</forename>
                   <roleName>Archdeacon of Canterbury</roleName>
                   <roleName>Lord Chancellor</roleName>
                </persName>
                <persName><addName>Thomas of London</addName></persName>
                <persName><addName>Saint Thomas of Canterbury</addName></persName>
                <persName><addName>Thomas à Becket</addName></persName>
                <birth when="1118-12-21">
                   <placeName>London, England</placeName></birth>
                <death when="1170-01-29">
                   <placeName>Canterbury, Kent, England</placeName></death>
                <occupation type="government" subtype="politician"/>
                <occupation type="religious" subtype="priest"/>
                <note resp="#jgf #lmw #rnes">As Archbishop of Canterbury, Becket quarreled with King Henry II over the balance of power between the church and crown. Becket was murdered by four knights while at prayer in Canterbury Cathedral. The king had reportedly been heard to ask the four knights "Will no one rid me of this meddlestome priest?," thereby calling for Becket's assassination without literally ordering it. Becket was canonized by the Roman Catholic Church as a saint in 1173.</note>
                <note><ref target="http://viaf.org/viaf/100187947"/></note>
             </person>`

**Comment by ebeshero** [comment]
@lmwilson Thanks! I found the problem once I opened my computer and took a look at the files. I just pushed a repair, so the occupation element is known and accounted for in its usual TEI location. I needed to change an attribute on the si_ODD file and regenerate the schema. Do a `git pull` and try it now! Does it work?

By the way, good work with the tic marks! If you do three in a row above and below a block, it preserves the formatting/indenting.

**Comment by ebeshero** [comment]
@lmwilson I found a couple of errors in my si_ODD schema just now and fixed them! I tested a bit on the si-Add for Charles I, Finden's and Rienzi and I think it's working properly (what it's flagging looks legit to me). Take a look and let me know if anything seems strange.

Also, do we want to add some of those occupations it's flagging to the schema?
