### ISSUE TITLE
Site Index updated

### ISSUE THREAD

**Issue by lmwilson** [DigitalMitford/DM_SiteIndex#8]
Si-Add poem titles file added.  Ready to activate for web. 1192 entries.  (Is this message okay? Was not sure what to call last step you need to do. )

**Comment by ebeshero** [comment]
Yes, that's perfect! Thanks @lmwilson !

**Comment by ebeshero** [comment]
@lmwilson I inspected the `si.xml` file and noticed there was a bug in my `AlphaSort.xsl` file that was generating a layer of `<roleName>` element around Mitford editor affiliation lines, every time we ran it. I repaired it and updated the si once more, and then sent it up to the website. 

Also just in case of any updates in the editing team list, I ran another XSLT to update our staff page on the website. Thanks for  all your work on this! I skimmed through the entries and they look good, and the schema is calm. :-)
