### ISSUE TITLE
Updating Site Index: Drama New & Revised entry list

### ISSUE THREAD

**Issue by lmwilson** [DigitalMitford/DM_SiteIndex#9]
Starting work on adding next list to SI.

**Comment by ebeshero** [comment]
Pinging vs. Assigning: According to GitHub, you've assigned me this issue (or "ticket"/ to-do). I'm happy to help with the Drama list, but I suspect you just meant to alert me that you're working on it. If you're just alerting me, a "ping" will do (which is old-fashioned submarine for sending a notification)--it works here just like in Box. Use the `@` symbol and my GitHub name: @ebeshero to send me a notification and I'll get it in my email. (I get it this way, too, but "Assigneees" means literally people working on this particular task.)  @lmwilson
